version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: